# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'FirstTV' do
pod "XCDYouTubeKit", "~> 2.5"
end

target 'FirstTVTests' do

end

target 'FirstTVUITests' do

end

